---
- hosts: all
  become: yes

  vars_files:
   - vars/credentials.yml
   - vars/main.yml

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks: 
  - name: Print environment HOME 
    debug: 
        msg: "{{ lookup('env','HOME') }}"
  - name: Ensure apt cache is updated
    apt: update_cache=true cache_valid_time=600
  - name: Install required apt packages 
    apt:
      name:
        - python3-pip
      state: present
  - name: Set root password
    user:
      name: root
      state: present
      update_password: always
      password: "{{ root_password }}"
  - name: remove vbox guest additions packages
    apt:
      name: 
        - virtualbox-guest-x11
        - virtualbox-guest-dkms
        - virtualbox-guest-utils
      state: absent
  - name: download vbox guest additions iso
    get_url:
      url: "{{ vb_guest_additions_url }}"
      dest: /opt
      mode: '0655'
  - name: Install pipenv 
    pip:
      name: pipenv
      executable: pip3
    become_user: root
  tasks:
    - import_tasks: tasks/aquatone.yml
    - import_tasks: tasks/bloodhound.yml
    - import_tasks: tasks/brutespray.yml
    - import_tasks: tasks/crackmapexec.yml
    - import_tasks: tasks/impacket.yml
    - import_tasks: tasks/krbrelayx.yml
    - import_tasks: tasks/mitm6.yml
    - import_tasks: tasks/privexchange.yml
    - import_tasks: tasks/responder.yml
    - import_tasks: tasks/sprayingtoolkit.yml
    - import_tasks: tasks/spray.yml
    - import_tasks: tasks/powershell.yml
#  - name: Install python3-pip
#    apt: name=python-pip state=present
#  - name: Install pipenv
#    command: pip3 install --user pipenv
