---
- name: CME clone repo
  git:
    repo: https://github.com/byt3bl33d3r/crackmapexec
    recursive: yes
    dest: "/opt/crackmapexec"
  become_user: root
- name: Install Poetry 
  shell: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  args: 
    chdir: "/opt/crackmapexec"
    warn: no
- name: Install CME 
  environment:
    PATH: "{{ ansible_env.HOME }}/.poetry/bin:{{ ansible_env.PATH }}"
  shell: |
    ~/.poetry/bin/poetry install 
  args: 
    chdir: "/opt/crackmapexec"
- name: CME Docker pull - cme
  shell: |
    docker pull byt3bl33d3r/crackmapexec